### ISSUE TITLE
Question About LRU Cache Key Implementation

### ISSUE THREAD

**Issue by HsinHeng** [nearform/fast-jwt#503]
Hi All, Thank you to contribute this awesome libs.

I have found that cache is use `hash(token)` as key, not direct to use `token` as key.
hash(token) spend a little time complexity, can we directly use `token` as key?

**Comment by simoneb** [comment]
@HsinHeng have you tested what kind of performance degrade the hashing is introducing?

**Comment by simoneb** [comment]
Thanks for the detailed feedback, much appreciated!

Ok so, based on your benchmarks above, it definitely does look like getting rid of the hashing would definitely improve the performance, so I'm happy to do that. 

We discussed it offline with @ilteoood and what we propose to do is allowing to override the cache key generation algorithm, but still defaulting to the existing one, primarily to avoid breaking changes and by staying conservative in terms of security and collision.

Would that work for you? Basically, if we do this, what you'd do in order to skip the hashing would be to pass the identity function to the cache key generator option.

**Comment by HsinHeng** [comment]
> Thanks for the detailed feedback, much appreciated!
> 
> Ok so, based on your benchmarks above, it definitely does look like getting rid of the hashing would definitely improve the performance, so I'm happy to do that.
> 
> We discussed it offline with @ilteoood and what we propose to do is allowing to override the cache key generation algorithm, but still defaulting to the existing one, primarily to avoid breaking changes and by staying conservative in terms of security and collision.
> 
> Would that work for you? Basically, if we do this, what you'd do in order to skip the hashing would be to pass the identity function to the cache key generator option.

Sometime I design jwt verify in node.js or gateway like kong ingress/nginx-plus based on different products. 
When I design jwt verify in gateway, my node.js app just only do jwt decode.

Actually I am looking for decode cache.😆

But I am inspired of your libs, that's awesome.
It's useful to me. Thanks a lot.
