### ISSUE TITLE
Add the decoded token to `key` function

### ISSUE THREAD

**Issue by mcollina** [nearform/fast-jwt#64]
`createVerifier()` accepts an ` async key()` option to fetch the key. We should pass in the decoded token to better support JWKS.

**Comment by panva** [comment]
Suggestion: provide just the JWT header, otherwise you're opening up the mistake people make of fetching unintended JWKS based on the `iss` claim. Header is enough to select a JWK from a Set.

**Comment by simoneb** [comment]
@panva I'm not sure I understand the suggestion. 

The domain from which to fetch the keys comes from the token payload's `iss` claim. If you don't expose this you'll have to make assumptions about where to get the keys from. Because often the tokens you're verifying are generated by external services you don't have control over, you can't make assumptions about where to get the keys from unless you have a token at hand.

So I'm not sure how this is going to work if you don't grab the url from.

**Comment by simoneb** [comment]
Based on what I see this is already being done (only the header is provided) https://github.com/nearform/fast-jwt/blob/a2dabad/src/verifier.js#L284. Do we agree that we need to provide both the header and the payload to be able to retrieve a key, say, using JWKS?

**Comment by panva** [comment]
Blindly trusting the `iss` claim to load any JWKS from the internet is a problem, so, as long as it comes with a big warning that you should only load JWKS from expected sources... fine

**Comment by simoneb** [comment]
> Blindly trusting the `iss` claim to load any JWKS from the internet is a problem, so, as long as it comes with a big warning that you should only load JWKS from expected sources... fine

Say you have a token that's generated by Auth0 or AWS Cognito. How do you know what iss those services decide to use? For Cognito, for instance, it's not even a static url. You can create that statically, I'm just wondering if that's safe or if those services could change that anytime and your application is broken when that happens.

**Comment by panva** [comment]
`iss` is generally an agreed upon value.

**Comment by simoneb** [comment]
In that case I believe there's nothing to do here. when it's a function, `key` is already invoked with the decoded token header.

**Comment by simoneb** [comment]
Closing this, it's already working as desired and we provide jwks via [get-jwks](https://github.com/nearform/get-jwks/)

**Comment by harcipulyka** [comment]
I believe the whole decoded JWT should be passed to the `key` function, because otherwise I have to manually decode it before verifying the signature, to get the issuer and based on that supply the right `key` function with the correct jwks fetcher method. And assuming that they are using the suggested jwks library (get-jwks), then it's not a security risk, because therer the `buildGetJwks` method has that security built in with the `allowedDomains` parameter, where you could specify which issuers are accepted.

**Comment by ilteoood** [comment]
@harcipulyka 
I think that for this situation you could use the `kid` header.

Here is an example (in Go, sorry) of something that should be really close to your case:
https://github.com/MicahParks/keyfunc/blob/master/keyfunc.go#L19
